name: Build/release
on:
  workflow_dispatch:
    inputs:
      # release:
      #   description: "Make a release (true/false)"
      #   required: true
      #   default: "false"
      artifacts:
        description: "Build artifacts (true/false)"
        required: true
        default: "false"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
          API_KEY: '${{ secrets.OPENWEATHER_APIKEY }}'
          # goddamn quotes
        run: |
          npm ci
          echo "module.exports.OPENWEATHER_APIKEY = $API_KEY" > env.js
          cat env.js
          npm run dist

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     release: ${{ github.event.inputs.release == 'true'}}
        # env:
          # OPENWEATHER_APIKEY: ${{ secrets.OPENWEATHER_APIKEY }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload artifacts
        if: ${{ github.event.inputs.artifacts == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            dist/Saeae*.exe
            dist/Saeae*.AppImage
            dist/Saeae*.deb
            !dist/win-unpacked/
