name: Build/release
on:
  workflow_dispatch:
    inputs:
      artifacts:
        description: "Build artifacts (true/false)"
        required: true
        default: "false"
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.OPENWEATHER_APIKEY }}
        run: |
          npm ci
          echo "module.exports.OPENWEATHER_APIKEY = '$API_KEY'" > env.js
          npm run dist

      - name: Upload artifacts
        if: ${{ github.event.inputs.artifacts == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            dist/Saeae*.exe
            dist/Saeae*.AppImage
            dist/Saeae*.deb
            !dist/win-unpacked/
